### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by iva585** [iva585/capstone-project#3]
## Value Proposition

As a user, I need to write down the food inventory I have at home, in order to optimize meal planning and simplify the creation of a shopping list.

## Description

The sketch below shows the inventory page when first rendered. Clicking on the green plus button pops the input field up, as seen on the second sketch.

<img width="344" alt="inventory button inactive" src="https://user-images.githubusercontent.com/90032497/142898634-8fe4a5f8-32c5-4e17-a5a3-b6f08fd13317.png">

This sketch shows the inventory after the green plus button has been clicked on. The input field is rendered, and submit (add) button is inactive, as long as the input field is empty. The green button now shows an x and is used to cancel adding the item to the shopping list. Upon clicking on it, the input field disappears. If an item is crossed out, a plus button is rendered next to it, which adds the item to the shopping list when clicked.

<img width="347" alt="inventory button active" src="https://user-images.githubusercontent.com/90032497/142898746-a8c98214-7cce-4a40-8e51-83ffa267ac4a.png">

## Acceptance Criteria

- [x] input field emerges when a user clicks on the plus button
- [x] on plus button click, the plus button 
- [x]  add button is inactive as long as the input field is empty
- [x] on add button click the item gets added to the list along with a checkbox
- [x] on add button click the input field disappears
- [x] on checkbox click the item gets crossed out
- [x] on checkbox click the item is moved to the end of the list
- [x] on checkbox click an add button  appears next to the item, which adds the item to shopping 
  list
- [x] on text click, the user can edit or delete the item
- [x]  max. number of characters is 50

## Tasks

- [x] Create Inventory Page
- [x] update Header component
- [x] update Footer component  with icons routed to shopping list and inventory
- [x] add Button component
- [x] add Form component
- [x] add List component
